{{- if .Values.crds.install }}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
{{ $.Files.Get $path }}
{{- end }}
{{- end }} 